sudo: required
dist: trusty
group: edge

language: node_js

os:
  - linux

node_js:
  - '6'

env:
  global:
    - secure: "GFlTN+Q3plut4OO0tD0Sb87La1nZRs6kZx2ZvXYGVoH0Ynegl8hAKQzzDVlqL7cqf+3oaWJ1wlCNgigMQ8nTwkguhw+IuzrN/cEgVxCUEY6iP5NhZ0dVSApDovCscwkN4A2e3BHuw9ZxWozAWpicmmyNfGXcLDEEqJDfMY8J/mEMJ07W6mao7fo9Jw073u8FVC3guHyl27PGGlZoZVkNbU7SmE4xlhuIldBQqFbyB8I9A5OG01+jB1ZykVBo+ytz9HhyVzLHfD1L9urGjPlBywB9f47P/f3qi7Is5MmJ6OZo0PhqlDZDFpPUInD0LY/kxLP4oncJTZL0Au2T/lHXe4Wz8y1F1fAeGgwE7LfULCAlf/P7vNoQ4a4WHmUJuKjLYCO+7uP3L6zUdxa/HY2701bvFoO5oUFeCxuy4vx5ltFnYWT4xair5j4zbRvZJ+B9ZkXbjz2tNd7cssb4G381fz2ekSqcvkERsWHMpJ1dSVFpaFGiO6NY/2dPy76Xx5IU9GwOA8coJ9na9V47FRYichlmOlq8UT5ZaYjp1VoJbtGHDnYru7EfUEHtw9jVOjb2OKO/uXc0UJdXUpRhcd87GPt4cUqT8fu1k5ouPhKopA+wSze+SV7ElBzelIzooabITTkGmyUzgqG+gcTa+eHWNclokN0XbBv85G42EBaRhBM=" # GITHUB_TOKEN

branches:
  only:
    - master

before_install:
  - npm --version

script:
  - npm run build

after_success:
  - npm run deploy
